Repository sparcs-kaist/taxi-front, pull requests merged in 2022-10, with the labels that each got.

#234 #206 sort search result and paging
  src/components/Search/SideResult.jsx
  src/components/common/pagination/Pagination.tsx
Labels: searchroom

#258 #257 테마에 zIndex 추가
  src/components/Chatting/Header/FullChatHeader.jsx
  src/components/Chatting/MessagesBody/ImageFullscreen.jsx
  src/components/Mypage/PopupMypage/PopupMypage.jsx
  src/components/Mypage/PopupSparcs/PopupSparcs.jsx
  src/components/Skeleton/Navigation.jsx
  src/components/common/HeaderBar.tsx
  src/components/common/modal/Modal.jsx
  src/components/common/roomOptions/Popup.jsx
  src/styles/theme.ts
Labels: common

#260 #259 marginAuto의 default 값 수정
  src/components/AddRoom/AddRoom.jsx
  src/components/Error/Error.jsx
  src/components/Mypage/Mypage.jsx
  src/components/Myroom/R1Myroom.jsx
  src/components/Myroom/R2Myroom.jsx
  src/components/Search/RoomSelectionModal.jsx
  src/components/Search/Search.jsx
  src/components/Search/SideResult.jsx
  src/components/common/Title.jsx
  src/components/common/WhiteContainer.jsx
  src/components/common/roomOptions/Date.jsx
  src/components/common/roomOptions/MaxPartLength.jsx
  src/components/common/roomOptions/Name.jsx
  src/components/common/roomOptions/Place.jsx
  src/components/common/roomOptions/Time.jsx
Labels: common

#249 #248 방 개설 페이지 리팩토링 및 스타일링
  package-lock.json
  package.json
  src/components/AddRoom/AddRoom.tsx
  src/components/Error/Error.jsx
  src/components/Login/Login.jsx
  src/components/Search/RoomSelectionModal.jsx
  src/components/Search/Search.jsx
  src/components/common/Button.tsx
  src/components/common/RLayout.jsx
  src/components/common/roomOptions/DatePicker.jsx
  src/components/common/roomOptions/MaxPart.jsx
  src/components/common/roomOptions/Name.tsx
  src/components/common/roomOptions/Place.jsx
  src/components/common/roomOptions/Popup.css
  src/components/common/roomOptions/Popup.jsx
  src/components/common/roomOptions/Time.jsx
  src/styles/theme.ts
  yarn.lock
Labels: newroom

#266 Refactor: modify robot.txt to prevent crawling
  public/robots.txt
Labels: ⚒ enhancement

#270 #263 Datepicker 색상 변경
  src/components/common/roomOptions/Date.jsx
  src/components/common/roomOptions/DatePicker.jsx
  src/styles/theme.ts
Labels: newroom, searchroom

#281 #280 만든 사람들 리스트를 json 형태로 저장
  src/static/members.js
Labels: mypage

#283 #274 "빠른 출발 검색" 및 툴팁 제작
  src/components/Search/Search.jsx
  src/components/common/Tooltip.tsx
Labels: searchroom, common

#284 #275 검색 조건 순서 변경 및 default 옵션 추가
  src/components/Search/Search.jsx
Labels: searchroom

#285 #269 모달 백그라운드 스크롤 막기
  src/components/common/modal/Modal.jsx
  src/components/common/roomOptions/Place.jsx
  src/components/common/roomOptions/Popup.jsx
  src/components/common/roomOptions/Time.jsx
  src/hooks/useDisableScroll.tsx
Labels: common

#276 #272 마이페이지 스타일링
  src/App.css
  src/components/Chatting/MessagesBody/ChatSet.jsx
  src/components/Mypage/Mypage.jsx
  src/components/Mypage/PopupMypage/PopupMypage.jsx
  src/components/Mypage/PopupPolicy/PopupPolicy.jsx
  src/components/Mypage/ProfileImg.jsx
  src/components/Search/Search.jsx
  src/components/Skeleton/Navigation.jsx
  src/components/common/Title.jsx
  src/styles/theme.ts
Labels: mypage

#262 내 방에 Pagination 추가
  package-lock.json
  package.json
  src/components/Myroom/Myroom.jsx
  src/components/Myroom/R1Myroom.jsx
  src/components/Myroom/R1Myroom.tsx
  src/components/Myroom/R2Myroom.jsx
  src/components/Search/Search.jsx
  src/components/Search/SideResult.jsx
  src/components/common/pagination/Pagination.tsx
  src/hooks/usePageFromSearchParams.tsx
  yarn.lock
Labels: myroomlist

#278 #277 Modal 수정 및 마이페이지 적용
  src/App.css
  src/components/Chatting/Header/Popup/PopupContainer.jsx
  src/components/Mypage/Mypage.jsx
  src/components/Mypage/PopupMembers.jsx
  src/components/Mypage/PopupModify.jsx
  src/components/Mypage/PopupMypage/PopupMypage.jsx
  src/components/Mypage/PopupMypage/svg_close.svg
  src/components/Mypage/PopupPolicy.jsx
  src/components/Mypage/PopupPolicy/svg_close.svg
  src/components/Mypage/PopupSparcs/PopupSparcs.jsx
  src/components/Search/RoomSelectionModal.jsx
  src/components/Skeleton/AlertProvider.jsx
  src/components/Skeleton/Skeleton.jsx
  src/components/common/RLayout.jsx
  src/components/common/modal/Modal.jsx
  src/hooks/useReactiveState.jsx
  src/styles/theme.ts
Labels: mypage, common

#288 roomOptions 내 컴포넌트 타입스크립트 전환
  .eslintrc.json
  src/components/AddRoom/AddRoom.tsx
  src/components/Search/Search.jsx
  src/components/common/roomOptions/Date.tsx
  src/components/common/roomOptions/MaxPart.tsx
  src/components/common/roomOptions/MaxPartLength.tsx
  src/components/common/roomOptions/Name.tsx
  src/components/common/roomOptions/Popup.tsx
  src/components/common/roomOptions/Time.tsx
  src/types/global.d.ts
  src/types/react-mobile-picker-mod.d.ts
  tsconfig.json
Labels: ⚒ enhancement

#294 #293 에러 페이지 수정
  src/components/Error/Error.jsx
  src/components/Error/Error.tsx
  src/components/Skeleton/Skeleton.jsx
  src/components/common/utils/Spacer.jsx
Labels: common

#292 #187 방이 없을 경우를 위한 Empty 컴포넌트 제작
  src/components/Myroom/R1Myroom.tsx
  src/components/Myroom/R2Myroom.jsx
  src/components/Search/SideResult.jsx
  src/components/common/Empty.tsx
Labels: common

#295 #268 참여 가능한 방 5개로 제한
  src/App.css
  src/components/AddRoom/AddRoom.tsx
  src/components/AddRoom/FullParticipation.tsx
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/Header/Popup/PopupCancel.jsx
  src/components/Myroom/Myroom.jsx
  src/components/Myroom/R2Myroom.jsx
  src/components/Search/RoomSelectionModal.jsx
  src/components/Search/SideResult.jsx
  src/components/Skeleton/Skeleton.jsx
  src/components/common/Title.jsx
  src/components/common/WhiteContainer.jsx
  src/recoil/myRoom/atom.ts
  src/recoil/myRoom/index.ts
  src/styles/theme.ts
Labels: newroom, myroomlist

#298 #297 Room 컴포넌트 스타일 수정
  src/components/AddRoom/FullParticipation.tsx
  src/components/Mypage/PopupMembers.jsx
  src/components/Mypage/PopupModify.jsx
  src/components/Search/SideResult.jsx
  src/components/common/room/Room.css
  src/components/common/room/Room.jsx
  src/styles/theme.ts
Labels: common

#302 pagination refactoring
  src/components/Myroom/Myroom.jsx
  src/components/Search/SideResult.jsx
  src/hooks/usePageFromSearchParams.tsx
Labels: 🔨refactoring

#303 #301 logininfo API 과다 호출 문제
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/Header/HeaderBody.jsx
  src/components/Mypage/PopupPolicy.jsx
  src/components/Skeleton/Skeleton.jsx
Labels: myroomlist
