Repository sparcs-kaist/taxi-front, pull requests merged in 2022-09, with the labels that each got.

#227 #217 use query on search
  package-lock.json
  package.json
  src/components/AddRoom/AddRoom.jsx
  src/components/Search/Search.jsx
  src/components/common/roomOptions/Date.jsx
  src/components/common/roomOptions/DatePicker.jsx
  src/components/common/roomOptions/Place.jsx
  yarn.lock
Labels: searchroom

#231 fix: change channelio name from id to name
  src/components/Skeleton/ChannelTalk.jsx
Labels: 😱 bug

#233 #232 Enable Typescript
  .eslintrc.json
  .prettierrc.json
  package-lock.json
  package.json
  yarn.lock
Labels: tool

#241 fix: style에 React.CSSProperties 타입 적용
  src/components/common/Button.tsx
Labels: 😱 bug

#207 #205 ios android web app setting
  public/index.html
  public/manifest.json
  src/App.css
  src/components/Login/Login.jsx
  src/components/Skeleton/Navigation.jsx
  src/components/Skeleton/Skeleton.jsx
Labels: skeleton

#243 #242 다양한 환경에 대응하기 위한 아이콘 설정
  public/apple-touch-icon.png
  public/favicon.ico
  public/icon.svg
  public/icons-192.png
  public/icons-512.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: common

#244 #185 DottedLine 컴포넌트 추가
  src/components/Chatting/Header/FullChatHeader.jsx
  src/components/Mypage/PopupMypage/PopupMypage.jsx
  src/components/Mypage/PopupSparcs/PopupSparcs.jsx
  src/components/Myroom/R2Myroom.jsx
  src/components/Search/RoomSelectionModal.jsx
  src/components/common/DottedLine.tsx
  src/components/common/room/Room.jsx
  src/components/common/roomOptions/DatePicker.jsx
  src/components/common/roomOptions/Place.jsx
  src/styles/theme.ts
Labels: common

#246 #245 로그인 페이지 리팩토링 및 스타일링
  src/components/Login/Login.jsx
  src/components/Skeleton/Skeleton.jsx
  src/components/common/Button.tsx
  src/components/common/HeaderBar.tsx
  src/static/assets/TaxiLogo.svg
Labels: loginpage

#238 #189 Add fullscreen Image
  package-lock.json
  src/components/Chatting/MessagesBody/ChatSet.jsx
  src/components/Chatting/MessagesBody/ImageFullscreen.jsx
  src/components/Chatting/MessagesBody/MessagesBody.jsx
  yarn.lock
Labels: chatting

#256 PR Template 수정
  .github/pull_request_template.md
Labels: documentation
