Repository sparcs-kaist/taxi-front, pull requests merged in 2022-05, with the labels that each got.

#95 #75 Fix Search UI and implement Search
  src/App.css
  src/components/Chatting/Header/Header.jsx
  src/components/Chatting/Style/MessagesBody.css
  src/components/Frame/DatePicker/DatePicker.jsx
  src/components/Frame/DatePicker/svg_left.svg
  src/components/Frame/DatePicker/svg_right.svg
  src/components/Frame/DatePicker/svg_today.svg
  src/components/Frame/ReactiveLayout/RLayout.jsx
  src/components/Frame/SubmitButton/SubmitButton.jsx
  src/components/Frame/Title/Title.jsx
  src/components/Frame/WhiteContainer/WhiteContainer.jsx
  src/components/Room/Room/RoomElement1.jsx
  src/components/Search/AddRoom/AddRoom.jsx
  src/components/Search/Options/Date.jsx
  src/components/Search/Options/Name.jsx
  src/components/Search/Options/Place.jsx
  src/components/Search/Options/Popup.css
  src/components/Search/Options/Popup.jsx
  src/components/Search/Options/Time.jsx
  src/components/Search/Search/Search.jsx
  src/components/Search/SearchResult/SideResult.jsx
  src/components/Setting/PopupMypage/PopupMypage.jsx
  src/components/Setting/PopupSparcs/PopupSparcs.jsx
Labels: searchroom, 🙌 review requested

#106 #103 Fix scroll to bottom
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/MessagesBody/MessagesBody.jsx
  src/components/Chatting/Style/MessagesBody.css
Labels: chatting, 🙌 review requested, do-not-merge-yet

#117 #115 Fix Setting to MyPage & Fix navigation bar
  src/App.css
  src/App.js
  src/asset/SparcsLogoBlack.svg
  src/asset/SparcsLogoPurple.svg
  src/asset/SparcsLogoYellow.svg
  src/components/Chatting/Header/Header.jsx
  src/components/Frame/Frame.jsx
  src/components/Frame/Navigation.css
  src/components/Frame/Navigation.jsx
  src/components/Frame/Title/Title.jsx
  src/components/Login/Login.jsx
  src/components/MyPage/MyPage.jsx
  src/components/MyPage/PopupMypage/PopupMypage.jsx
  src/components/MyPage/PopupMypage/svg_close.svg
  src/components/MyPage/PopupPolicy/PopupPolicy.jsx
  src/components/MyPage/PopupPolicy/svg_close.svg
  src/components/MyPage/PopupSparcs/PopupSparcs.jsx
  src/components/Room/Room/RoomElement1.jsx
  src/components/Search/AddRoom/AddRoom.jsx
  src/components/Search/AddRoom/svg_add.svg
  src/components/Search/Search/Search.jsx
  src/components/Search/Search/svg_search.svg
  src/components/Search/SearchResult/SearchResult.jsx
  src/components/Search/SearchResult/SideResult.jsx
  src/components/Search/SearchResult/svg_result.svg
  src/components/Setting/PopupSparcs/svg_close.svg
  src/components/Setting/PopupSparcs/svg_sparcs1.svg
  src/components/Setting/svg_document.svg
  src/components/Setting/svg_logout.svg
  src/components/Setting/svg_myPage.svg
  src/components/room/Myroom/Myroom.jsx
  src/images/x-symbol.svg
Labels: 🙌 review requested

#126 #123-modify-roomInfo-api-calling
  src/components/Chatting/Chatting.jsx
Labels: 🙌 review requested

#131 Refactor: modify addRoom api
  src/components/Search/AddRoom/AddRoom.jsx
Labels: 😱 bug

#133 Refactor: modify chatting api
  src/components/Chatting/Chatting.jsx
Labels: 😱 bug, chatting
