Repository sparcs-kaist/taxi-front, pull requests merged in 2022-08, with the labels that each got.

#159 #139 방 개설 페이지 default time 버그
  src/components/Frame/DatePicker/getDateInfo.js
  src/components/Search/AddRoom/AddRoom.jsx
  src/components/Search/Search/Search.jsx
  src/tools/trans.js
Labels: 😱 bug, newroom, searchroom

#163 #162 mypage axios refactoring
  src/components/Frame/useTaxiAPI/useTaxiAPI.jsx
  src/components/Mypage/Mypage.jsx
  src/components/Mypage/PopupMypage/PopupMypage.jsx
Labels: ⚒ enhancement, mypage

#164 #160 maximum people number setting
  src/components/Frame/Counter/Counter.jsx
  src/components/Search/AddRoom/AddRoom.jsx
  src/components/Search/Options/MaxPartLength.jsx
  src/components/Search/Search/Search.jsx
Labels: newroom, searchroom

#158 #140 채팅에서 s3를 사용한 이미지 전송
  package-lock.json
  package.json
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/Header/FullChatHeader.jsx
  src/components/Chatting/Header/Header.jsx
  src/components/Chatting/Header/SideChatHeader.jsx
  src/components/Chatting/Input/FullChatMessageForm.jsx
  src/components/Chatting/Input/MessageForm.jsx
  src/components/Chatting/Input/NewMessage.jsx
  src/components/Chatting/Input/SideChatMessageForm.jsx
  src/components/Chatting/MessagesBody/ChatDate.jsx
  src/components/Chatting/MessagesBody/ChatInOut.jsx
  src/components/Chatting/MessagesBody/ChatMessage.jsx
  src/components/Chatting/MessagesBody/ChatSet.jsx
  src/components/Chatting/MessagesBody/MessagesBody.jsx
  src/components/Chatting/MessagesBody/NewMessage.jsx
  src/components/Chatting/MessagesBody/UserAvatar.jsx
  src/components/Chatting/Style/MessageForm.css
  src/components/Chatting/Style/MessagesBody.css
  src/components/Chatting/Style/NewMessage.css
  src/components/Chatting/Style/SideChatMessageForm.css
  src/components/Chatting/Style/UserAvatar.css
  yarn.lock
Labels: 😱 bug, chatting, 🙌 review requested

#171 #144 create error handling page
  .gitignore
  src/App.js
  src/components/Error/Error.jsx
  src/components/common/Title.jsx
  src/components/common/roomOptions/SubmitButton.jsx
  src/components/common/utils/Spacer.jsx
Labels: 🙌 review requested

#172 #170 myroom refactoring
  src/components/Chatting/MessagesBody/MessagesBody.jsx
  src/components/Error/Error.jsx
  src/components/Myroom/ArrowBack.svg
  src/components/Myroom/Myroom.jsx
  src/components/Myroom/R1Myroom.jsx
  src/components/Myroom/R2Myroom.jsx
  src/components/Myroom/Send.svg
  src/components/Myroom/chatIcon.svg
  src/components/Myroom/svg_room.svg
  src/components/Search/SideResult.jsx
  src/components/Skeleton/Navigation.jsx
  src/components/common/Title.jsx
  src/components/common/room/Room.jsx
  src/components/common/room/RoomList.jsx
Labels: myroomlist

#174 #173 chatting messageform refactoring
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/Input/FullChatMessageForm.jsx
  src/components/Chatting/Input/SideChatMessageForm.jsx
  src/components/Chatting/MessageForm/FullChatMessageForm.jsx
  src/components/Chatting/MessageForm/MessageForm.jsx
  src/components/Chatting/MessageForm/NewMessage.jsx
  src/components/Chatting/MessagesBody/ChatSet.jsx
  src/components/Chatting/MessagesBody/MessagesBody.jsx
  src/components/Chatting/Style/MessageForm.css
  src/tools/regExpTest.js
Labels: chatting

#177 #166 change location scheme
  src/components/AddRoom/AddRoom.jsx
  src/components/Search/Search.jsx
  src/components/Search/SideResult.jsx
  src/components/common/roomOptions/Place.jsx
  src/hooks/useTaxiAPI.jsx
  src/tools/trans.js
Labels: newroom, searchroom

#179 [Bug] Socket.io handshake is not established under reverse proxy
  .env.example
  src/components/Chatting/Chatting.jsx
  src/serverconf.js
Labels: 😱 bug, chatting

#183 #167 add room modal
  src/components/Search/RoomSelectionModal.jsx
  src/components/Search/SideResult.jsx
  src/components/common/modal/Modal.jsx
  src/components/common/room/Room.jsx
Labels: searchroom

#192 #190 채널톡 서비스를 사용한 문의하기
  src/App.js
  src/components/Login/Login.jsx
  src/components/Mypage/Mypage.jsx
  src/components/Skeleton/ChannelTalk.jsx
  src/serverconf.js
  src/tools/channelService.js
Labels: mypage

#193 #191 사용자 약관 수정
  src/components/Mypage/PopupPolicy/PopupPolicy.jsx
  src/hooks/useReactiveState.jsx
Labels: mypage

#176 #175 chatting header refactoring 1
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/Header/FullChatHeader.jsx
  src/components/Chatting/Header/HeaderBody.jsx
  src/components/Chatting/Header/Popup/PopupCancel.jsx
  src/components/Chatting/Header/Popup/PopupContainer.jsx
  src/components/Chatting/Header/SideChatHeader.jsx
  src/components/Chatting/Header/svg_back.svg
  src/components/Chatting/Header/svg_back_white.svg
  src/components/Chatting/Header/svg_close.svg
  src/components/Chatting/Header/svg_closeGray.svg
  src/components/Chatting/Header/svg_menu.svg
  src/components/Chatting/Style/SideChatHeader.css
  src/components/Myroom/R2Myroom.jsx
  src/components/Skeleton/Navigation.jsx
  src/components/Skeleton/Skeleton.jsx
Labels: chatting

#195 #188 introduce global state (location 적용)
  package-lock.json
  package.json
  src/App.js
  src/components/Skeleton/Skeleton.jsx
  src/components/common/roomOptions/Place.jsx
  src/recoil/preference/atom.js
  src/recoil/preference/index.js
  src/recoil/taxiLocation/atom.js
  src/recoil/taxiLocation/index.js
  src/recoil/taxiLocation/withName.js
  yarn.lock
Labels: newroom, searchroom, common

#200 #199 Wrapping moment
  package-lock.json
  src/components/AddRoom/AddRoom.jsx
  src/components/Chatting/Header/HeaderBody.jsx
  src/components/Chatting/MessagesBody/ChatSet.jsx
  src/components/Chatting/MessagesBody/MessagesBody.jsx
  src/components/Search/RoomSelectionModal.jsx
  src/components/Search/Search.jsx
  src/components/common/room/Room.jsx
  src/components/common/roomOptions/DatePicker.jsx
  src/tools/moment.js
  src/tools/trans.js
  yarn.lock
Labels: ⚒ enhancement

#194 #184 refactoring room component
  package-lock.json
  src/components/Chatting/Header/HeaderBody.jsx
  src/components/common/room/Room.jsx
  src/components/common/room/RoomElement.css
  src/components/common/room/RoomElement.jsx
  src/components/common/room/svg_arrow.svg
  yarn.lock
Labels: myroomlist

#198 #197 refactor roomselectionmodal
  src/components/Search/RoomSelectionModal.jsx
  src/components/Skeleton/Skeleton.jsx
  src/components/common/room/Room.jsx
  src/recoil/loginInfoDetail/atom.js
  src/recoil/loginInfoDetail/index.js
  src/tools/trans.js
Labels: searchroom, myroomlist

#209 #204 pass user info to channeltalk
  src/components/Skeleton/ChannelTalk.jsx
  src/tools/channelService.js
Labels: common

#210 #203 introduce AlertProvider
  src/App.js
  src/components/Mypage/PopupMypage/PopupMypage.jsx
  src/components/Skeleton/AlertProvider.jsx
  src/recoil/alert/atom.js
  src/recoil/alert/index.js
Labels: skeleton
