Repository sparcs-kaist/taxi-front, pull requests merged in 2022-07, with the labels that each got.

#135 #134 Fix style of pages and Refactor
  package-lock.json
  src/components/Frame/DatePicker/DatePicker.jsx
  src/components/Frame/Navigation.jsx
  src/components/Frame/Title/Title.jsx
  src/components/MyPage/MyPage.jsx
  src/components/MyPage/PopupSparcs/PopupSparcs.jsx
  src/components/Room/Myroom/Myroom.jsx
  src/components/Room/Room/RoomElement.css
  src/components/Room/Room/RoomElement.jsx
  src/components/Room/Room/RoomList.jsx
  src/components/Search/AddRoom/AddRoom.jsx
  src/components/Search/Options/Name.jsx
  src/components/Search/Options/Time.jsx
  src/components/Search/Search/Search.jsx
  src/components/Search/SearchResult/SideResult.jsx
  yarn.lock
Labels: 🙌 review requested

#143 #142 구 테스트용 페이지 제거
  src/App.js
  src/components/user/login.js
  src/components/user/newuser.js
  src/components/user/user.js
Labels: 🙌 review requested

#122 #111 모든 방 찾기 및 과거 방 검색 미허용
  src/components/Search/Search/Search.jsx
Labels: 🙌 review requested

#147 #142.1 구 테스트용 페이지 제거
  public/testCat.jpeg
  src/App.js
  src/components/Chatting/Header/Header.jsx
  src/components/Frame/DatePicker/DatePicker.jsx
  src/components/Frame/WhiteContainer/WhiteContainerMargin.jsx
  src/reportWebVitals.js
  src/setupTests.js
Labels: ⚒ enhancement

#152 #151 refactoring frame
  src/App.js
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/Header/Header.jsx
  src/components/Chatting/Header/SideChatHeader.jsx
  src/components/Chatting/SideChat.jsx
  src/components/Chatting/WrapChat.jsx
  src/components/Frame/Frame.jsx
  src/components/Frame/Navigation.jsx
  src/components/Frame/Skeleton/Skeleton.jsx
  src/components/Room/Myroom/Myroom.jsx
  src/components/Room/Room/RoomList.jsx
  yarn.lock
Labels: 🙌 review requested

#153 #146 mypage naming issue
  src/App.js
  src/components/Frame/Skeleton/Skeleton.jsx
  src/components/Mypage/Mypage.jsx
  src/components/Mypage/PopupMypage/PopupMypage.jsx
  src/components/Mypage/PopupMypage/svg_close.svg
  src/components/Mypage/PopupPolicy/PopupPolicy.jsx
  src/components/Mypage/PopupPolicy/svg_close.svg
  src/components/Mypage/PopupSparcs/PopupSparcs.jsx
  src/components/Mypage/ProfileImg.jsx
  src/components/Search/AddRoom/AddRoom.jsx
Labels: mypage

#157 #156 Scroll Restoration
  package-lock.json
  package.json
  src/App.js
  yarn.lock
Labels: 🙌 review requested

#155 #96 fix scroll picker
  package-lock.json
  package.json
  src/App.js
  src/components/Search/Options/Place.jsx
  src/components/Search/Options/Time.jsx
  yarn.lock
Labels: 😱 bug, newroom, searchroom, 🙌 review requested
