Repository sparcs-kaist/taxi-front, pull requests merged in 2023-01, with the labels that each got.

#428 #427 [Bug] 인피니트 스크롤 시에 채팅 깜빡임 현상
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/MessagesBody/ChatDate.jsx
  src/components/Chatting/MessagesBody/ChatInOut.jsx
  src/components/Chatting/MessagesBody/MessagesBody.jsx
Labels: chatting

#393 #392 로그아웃 시 리다이렉트 주소 변경
  src/App.js
  src/components/Login/Logout.tsx
  src/components/Mypage/Mypage.jsx
  src/components/Skeleton/Skeleton.tsx
Labels: 🙌 review requested

#404 #403 새로운 방을 위한 랜덤 placeholder + cookie를 이용한 검색 기록 바탕 place 자동 완성
  src/components/AddRoom/AddRoom.tsx
  src/components/Search/Search.jsx
  src/components/common/roomOptions/Name.tsx
  src/static/randomRoomName.js
Labels: newroom, searchroom

#444 #443 logininfo와 rooms api call 통일
  cypress/utils/login.ts
  src/components/AddRoom/AddRoom.tsx
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/Header/Popup/PopupCancel.jsx
  src/components/Chatting/Header/Popup/PopupPay.jsx
  src/components/Chatting/Header/Popup/PopupSend.jsx
  src/components/Home/RoomSection.tsx
  src/components/Mypage/PopupPolicy.jsx
  src/components/Myroom/R2Myroom.jsx
  src/components/Search/RoomSelectionModal.jsx
  src/components/Search/Search.jsx
  src/components/Skeleton/Skeleton.tsx
Labels: ⚒ enhancement
