Repository sparcs-kaist/taxi-front, pull requests merged in 2023-03, with the labels that each got.

#436 #435 정산/결제 시 채팅 보내기
  src/components/Chatting/Header/Popup/PopupCancel.jsx
  src/components/Chatting/Header/Popup/PopupContainer.jsx
  src/components/Chatting/MessagesBody/ChatPaySettle.tsx
  src/components/Chatting/MessagesBody/ChatSet.jsx
  src/components/Chatting/MessagesBody/MessagesBody.jsx
  src/components/Chatting/Vector.png
  src/components/Myroom/R2Myroom.jsx
  src/components/Reporting/PopupReport.tsx
  src/components/common/modal/ButtonCancelOk.jsx
  src/components/common/room/Room.jsx
Labels: chatting

#454 #450 마이페이지 영어 지원
  package-lock.json
  package.json
  src/components/Mypage/Menu.tsx
  src/components/Mypage/Mypage.jsx
  src/components/Mypage/PopupModify.jsx
  src/components/Mypage/PopupReport/ReportList.tsx
  src/components/Mypage/PopupReport/ReportOption.tsx
  src/components/Mypage/PopupReport/index.tsx
  src/lang/i18n.js
  src/lang/mypage/en.json
  src/lang/mypage/ko.json
Labels: mypage

#459 #458 members.js에 2022겨울학기, 2023봄학기 반영
  src/static/members.js
Labels: mypage

#461 #329 TypeScript component의 defaultProps 사용 지우기
  src/components/Myroom/R1Myroom.tsx
Labels: common, 🔨refactoring

#460 #286 Hover 이벤트 통일
  package-lock.json
  package.json
  src/App.js
  src/components/Chatting/MessagesBody/ChatSet.jsx
  src/components/Chatting/MessagesBody/MessagesBody.jsx
  src/components/Home/Date.tsx
  src/components/Mypage/Menu.tsx
  src/components/Myroom/R2Myroom.jsx
  src/components/Search/Search.jsx
  src/components/Skeleton/ChannelTalkProvider/channelService.js
  src/components/Skeleton/ChannelTalkProvider/index.tsx
  src/components/Skeleton/Navigation.tsx
  src/components/Skeleton/ScrollRestoration.js
  src/components/common/Button.tsx
  src/components/common/RLayout.jsx
  src/components/common/roomOptions/DatePicker.jsx
  src/components/common/roomOptions/Place.jsx
  src/tools/hoverEventSet.ts
  src/tools/isMobile.ts
Labels: tool, 🔨refactoring

#469 #468 검색 페이지 랜더링 최적화
  src/components/Search/Search.jsx
  src/components/common/Title.jsx
  src/components/common/roomOptions/Date.tsx
  src/components/common/roomOptions/DatePicker.jsx
  src/components/common/roomOptions/MaxPeople.tsx
  src/components/common/roomOptions/Name.tsx
  src/components/common/roomOptions/Place.jsx
  src/components/common/roomOptions/Time.tsx
Labels: ⚒ enhancement, searchroom

#466 #465 개인정보처리방침 추가
  src/components/Mypage/Mypage.jsx
  src/components/Mypage/PopupPrivacyPolicy.tsx
  src/lang/mypage/en.json
  src/lang/mypage/ko.json
Labels: mypage

#464 #462 [Bug] ScrollRestoration이 검색 페이지와 내방리스트 페이지에서는 작동하지 않음
  package-lock.json
  package.json
  src/components/Skeleton/ScrollRestoration.js
  src/components/Skeleton/ScrollRestoration/index.tsx
  src/components/Skeleton/ScrollRestoration/utils.ts
Labels: searchroom, myroomlist, common

#467 #254 모바일 기기에서 입력시 키패드와 네비게이션 바 공존 해결
  package-lock.json
  src/App.js
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/MessageForm/FullChatMessageForm.jsx
  src/components/Chatting/MessageForm/MessageForm.tsx
  src/components/Skeleton/Navigation.tsx
  src/components/Skeleton/VirtualKeyboardDetector.tsx
  src/recoil/isVirtualKeyboardDetectedAtom.ts
Labels: 😱 bug

#438 [WiP] #437 Web Push 서비스 워커 추가
  .env.example
  .eslintrc.json
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/components/Chatting/Header/FullChatHeader.jsx
  src/components/Search/Search.jsx
  src/components/Skeleton/Skeleton.tsx
  src/components/common/Button.tsx
  src/serverconf.js
  src/tools/firebase.ts
Labels: ⚒ enhancement, chatting

#476 #475 [Bug] REACT_APP_FIREBASE_CONFIG 환경변수가 없으면 서비스 워커 추가 안함
  src/serverconf.js
  src/tools/firebase.ts
Labels: 😱 bug

#474 #463 package.json에서 사용하지 않는 package 지우기
  package-lock.json
  package.json
  src/App.test.js
Labels: ⚒ enhancement

#449 #440 계정정보 전송 및 변경
  package-lock.json
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/MessageForm/FullChatMessageForm.tsx
  src/components/Chatting/MessageForm/MessageForm.tsx
  src/components/Chatting/MessageForm/NewMessage.tsx
  src/components/Chatting/MessageForm/Popup/PopupAccount.tsx
  src/components/Chatting/MessagesBody/ChatPaySettle.tsx
  src/components/Chatting/MessagesBody/ChatSet.jsx
  src/components/Chatting/MessagesBody/MessagesBody.jsx
  src/components/Mypage/Mypage.jsx
  src/components/Mypage/PopupModify.jsx
  src/components/common/AccountSelector.tsx
  src/lang/mypage/en.json
  src/lang/mypage/ko.json
  src/recoil/loginInfoDetail/index.ts
  src/static/bankNames.ts
  src/styles/theme.ts
  src/tools/hoverEventSet.ts
  src/tools/regExpTest.js
Labels: ⚒ enhancement, mypage, chatting, 🖥 working

#477 #389 로그아웃 감지로직의 수정 + Introduce `useAxios` and `useQuery`
  src/App.js
  src/components/AddRoom/AddRoom.tsx
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/Header/Popup/PopupCancel.jsx
  src/components/Chatting/Header/Popup/PopupPay.jsx
  src/components/Chatting/Header/Popup/PopupSend.jsx
  src/components/Home/RoomSection.tsx
  src/components/Login/Logout.tsx
  src/components/Mypage/PopupModify.jsx
  src/components/Mypage/PopupPolicy.jsx
  src/components/Mypage/PopupReport/index.tsx
  src/components/Myroom/Myroom.jsx
  src/components/Myroom/R2Myroom.jsx
  src/components/Reporting/PopupReport.tsx
  src/components/Search/RoomSelectionModal.jsx
  src/components/Search/Search.jsx
  src/components/Skeleton/CSSVariablesProvider.tsx
  src/components/Skeleton/GoogleAnalyticsProvier.tsx
  src/components/Skeleton/Skeleton.tsx
  src/components/common/AccountSelector.tsx
  src/components/common/room/Room.jsx
  src/components/common/roomOptions/Place.jsx
  src/hooks/useTaxiAPI.jsx
  src/hooks/useTaxiAPI/axios.ts
  src/hooks/useTaxiAPI/index.tsx
  src/hooks/useTaxiAPI/useAxios.tsx
  src/hooks/useTaxiAPI/useQuery.tsx
  src/recoil/preference/atom.js
  src/recoil/preference/index.js
  src/recoil/taxiLocation/index.js
  src/recoil/taxiLocation/withName.js
  src/tools/axios.js
  src/tools/firebase.ts
  src/types/global.d.ts
Labels: common

#485 #483 FCM background 메시지 핸들러 변경
  public/firebase-messaging-sw.js
Labels: chatting

#490 #389.2 [Bug] logout 감지 안됨
  src/hooks/useTaxiAPI/useAxios.tsx
Labels: common

#492 #491 Introduce `useDateToken`
  src/hooks/useDateToken.tsx
  src/hooks/useTaxiAPI/useQuery.tsx
  src/pages/Chatting/index.jsx
  src/pages/Home/RoomSection.tsx
  src/pages/Mypage/index.jsx
  src/pages/Myroom/R2Myroom.jsx
Labels: common, 🔨refactoring

#486 #291 `Popup` 컴포넌트 `Modal`로 대체 및 `Popup` 제거 + Refactor `PopupModify`
  src/components/AccountSelector.tsx
  src/components/Modal.jsx
  src/components/RoomOptions/Place.jsx
  src/components/RoomOptions/Popup.tsx
  src/components/RoomOptions/Time.tsx
  src/pages/Chatting/MessageForm/Popup/PopupAccount.tsx
  src/pages/Mypage/PopupModify.jsx
  src/pages/Mypage/langs/en.json
  src/pages/Mypage/langs/ko.json
  src/tools/regExpTest.js
Labels: mypage, common, 🔨refactoring
