Repository sparcs-kaist/taxi-front, pull requests merged in 2023-08, with the labels that each got.

#607 #602 채팅 공유하기 메시지 추가
  src/components/Chat/MessagesBody/MessageSet/MessagePaySettlement.tsx
  src/components/Chat/MessagesBody/MessageSet/MessageShare.tsx
  src/components/Chat/MessagesBody/MessageSet/index.tsx
  src/components/Chat/index.tsx
  src/components/Link/LinkKakaotalkShare.tsx
  src/components/ModalPopup/Body/BodyNotificationGuide.tsx
  src/components/ModalPopup/Body/BodyPrivacyPolicy.tsx
  src/components/ModalPopup/Body/BodyRoomShare.tsx
  src/components/Skeleton/SocketToastProvider.tsx
  src/hooks/chat/useBodyScrollControllerEffect.tsx
  src/hooks/chat/useChatsForBody.tsx
  src/hooks/chat/useSocketChatEffect.tsx
  src/static/members.js
  src/tools/chat/chats.ts
  src/tools/random/index.ts
  src/tools/random/roomNames.ts
  src/tools/random/suggestRoomShareTexts.ts
  src/types/chat.d.ts
  src/types/global.d.ts
Labels: chatting

#611 #610 [Bug] .heic 이미지 업로드 하면 깨짐
  package.json
  pnpm-lock.yaml
Labels: 😱 bug

#608 #592.2 Nginx 컨테이너에서 `/invite` 페이지는 별도 파일 응답
  Dockerfile
  public/index.html
  serve/default.conf
  serve/invite.html
  src/components/Skeleton/Routes.tsx
  src/components/Skeleton/index.tsx
  src/pages/Invite/index.tsx
  src/tools/trans.js
  src/types/env.d.ts
Labels: ⚒ enhancement

#612 #592.3 `invite.html`에서 `redirectPath` 오타 수정
  serve/invite.html
Labels: 😱 bug
