Repository sparcs-kaist/taxi-front, pull requests merged in 2023-07, with the labels that each got.

#593 #592 공유하기 링크의 OG image URL 수정
  src/App.js
  src/components/Link/LinkKakaotalkShare.tsx
  src/components/ModalPopup/Body/BodyRoomShare.tsx
  src/components/Skeleton/ChannelTalkProvider/index.tsx
  src/components/Skeleton/FirebaseMessagingProvider.tsx
  src/index.js
  src/loadenv.js
  src/loadenv.ts
  src/pages/Chatting/Header/FullChatHeader.jsx
  src/types/env.d.ts
  src/types/global.d.ts
Labels: ⚒ enhancement

#596 #333 `AdaptiveDiv` as refactor `RLayout`
  src/components/AdaptiveDiv/AdaptiveButterfly.tsx
  src/components/AdaptiveDiv/AdaptiveCenter.tsx
  src/components/AdaptiveDiv/AdaptiveModal.tsx
  src/components/AdaptiveDiv/index.tsx
  src/components/Modal/ModalElem.tsx
  src/components/ModalRoomOptions/MaxPeople.tsx
  src/components/RLayout.jsx
  src/components/Title.tsx
  src/components/WhiteContainer/index.tsx
  src/hooks/useButterflyState.tsx
  src/hooks/useReactiveState.jsx
  src/pages/Addroom/FullParticipation.tsx
  src/pages/Addroom/index.tsx
  src/pages/Chatting/Header/FullChatHeader.jsx
  src/pages/Chatting/index.jsx
  src/pages/Event/Event2022Beta.jsx
  src/pages/Event/Event2023Spring.tsx
  src/pages/Home/EventSection.tsx
  src/pages/Home/InfoSection.tsx
  src/pages/Home/RoomSection.tsx
  src/pages/Home/SuggestAppSection.tsx
  src/pages/Mypage/index.tsx
  src/pages/Myroom/R1Myroom.tsx
  src/pages/Myroom/R2Myroom.jsx
  src/pages/Myroom/index.jsx
  src/pages/Search/index.jsx
  src/tools/theme.ts
Labels: common, 🔨refactoring

#590 #588 migrate pnpm
  .gitignore
  Dockerfile
  README.md
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/types/custom.d.ts
  tsconfig.json
Labels: 🔨refactoring
