Repository sparcs-kaist/taxi-front, pull requests merged in 2023-04, with the labels that each got.

#497 #403.3 chat-GPT4가 추천한 랜덤 방 이름들 randomRoomName 모듈에 추가
  src/pages/Chatting/MessageForm/FullChatMessageForm.tsx
  src/static/randomRoomName.js
Labels: ⚒ enhancement, newroom

#488 #394 마이페이지에 알림 설정 추가 + Introduce `@emotion/react`
  .eslintrc.json
  .prettierignore
  craco.config.js
  package-lock.json
  package.json
  src/atoms/deviceToken.ts
  src/atoms/notificationOptions.ts
  src/components/Room/index.jsx
  src/components/Skeleton/FirebaseMessagingProvider.tsx
  src/components/Skeleton/FirebaseMessagingProvider/firebase.ts
  src/components/Skeleton/FirebaseMessagingProvider/index.tsx
  src/components/Skeleton/I18nextProvider.jsx
  src/components/Skeleton/Navigation.tsx
  src/components/Skeleton/index.tsx
  src/components/Toggle.tsx
  src/pages/Addroom/langs/en.json
  src/pages/Addroom/langs/ko.json
  src/pages/Home/langs/en.json
  src/pages/Home/langs/ko.json
  src/pages/Mypage/Menu.tsx
  src/pages/Mypage/ModalNotification/Guide.tsx
  src/pages/Mypage/ModalNotification/index.tsx
  src/pages/Mypage/PopupMembers.jsx
  src/pages/Mypage/PopupPolicy.jsx
  src/pages/Mypage/PopupReport/index.tsx
  src/pages/Mypage/index.jsx
  src/pages/Mypage/index.tsx
  src/pages/Mypage/langs/en.json
  src/pages/Mypage/langs/ko.json
  src/pages/Myroom/langs/en.json
  src/pages/Myroom/langs/ko.json
  src/pages/Search/RoomSelectionModal.jsx
  src/pages/Search/langs/en.json
  src/pages/Search/langs/ko.json
  src/types/react-mobile-picker-mod.d.ts
  tsconfig.json
Labels: mypage

#500 #372: Introduce `ModalProvider`
  src/App.js
  src/atoms/modals.ts
  src/components/Modal.jsx
  src/components/Modal/ModalElem.tsx
  src/components/Modal/ModalProvider.tsx
  src/components/Modal/index.tsx
  src/components/RoomOptions/Place.jsx
  src/components/RoomOptions/Time.tsx
  src/components/Skeleton/AlertProvider.tsx
  src/hooks/useDateToken.tsx
  src/pages/Chatting/Header/Popup/PopupContainer.jsx
  src/pages/Chatting/MessageForm/FullChatMessageForm.tsx
  src/pages/Chatting/MessageForm/Popup/PopupAccount.tsx
  src/pages/Chatting/MessagesBody/PopupReport.tsx
  src/pages/Mypage/ModalNotification/index.tsx
  src/pages/Mypage/PopupMembers.jsx
  src/pages/Mypage/PopupModify.jsx
  src/pages/Mypage/PopupPolicy.jsx
  src/pages/Mypage/PopupPrivacyPolicy.tsx
  src/pages/Mypage/PopupReport/index.tsx
  src/pages/Search/RoomSelectionModal.jsx
  src/tools/theme.ts
Labels: common

#513 #512 웹/앱 여부 감지
  src/App.js
  src/atoms/deviceToken.ts
  src/atoms/loginInfoDetail.ts
  src/components/Skeleton/FirebaseMessagingProvider.tsx
  src/components/Skeleton/FlutterEventCommunicationProvider.tsx
  src/components/Skeleton/index.tsx
  src/pages/Mypage/ModalNotification/index.tsx
  src/pages/Mypage/PopupModify.jsx
  src/pages/Mypage/PopupPolicy.jsx
  src/tools/sendEventToFlutter.ts
  src/types/global.d.ts
Labels: common

#515 #514 lazy loading 코드 스플리팅
  src/App.css
  src/App.js
  src/components/Loading.tsx
  src/routes.ts
  src/tools/theme.ts
Labels: ⚒ enhancement

#517 #465.3 이용 약관에 개인정보 수집 및 이용 추가
  src/components/ModalPopup/PrivacyPolicy.tsx
  src/components/ModalPopup/Terms.tsx
  src/components/ModalRoomOptions/Date.tsx
  src/components/ModalRoomOptions/DatePicker.jsx
  src/components/ModalRoomOptions/MaxPeople.tsx
  src/components/ModalRoomOptions/Name.tsx
  src/components/ModalRoomOptions/Picker.css
  src/components/ModalRoomOptions/Picker.js
  src/components/ModalRoomOptions/Place.jsx
  src/components/ModalRoomOptions/Time.tsx
  src/components/ModalRoomOptions/index.tsx
  src/components/Skeleton/index.tsx
  src/pages/Addroom/index.tsx
  src/pages/Mypage/PopupPolicy.jsx
  src/pages/Mypage/PopupPrivacyPolicy.tsx
  src/pages/Search/index.jsx
Labels: mypage

#520 #254.4 IOS 환경에서의 가상키보드 활성화 시, 화면 가려짐 해결
  src/components/HeaderBar.tsx
  src/components/Room/index.jsx
  src/components/Skeleton/CSSVariablesProvider.tsx
  src/components/Skeleton/VirtualKeyboardDetector.tsx
  src/pages/Chatting/Container/index.tsx
  src/pages/Chatting/FullChat.tsx
  src/pages/Chatting/Header/FullChatHeader.jsx
  src/pages/Chatting/Header/Header.jsx
  src/pages/Chatting/Header/SideChatHeader.jsx
  src/pages/Chatting/Header/index.tsx
  src/pages/Chatting/MessageForm/FullChatMessageForm.tsx
  src/pages/Chatting/MessageForm/index.tsx
  src/pages/Chatting/MessagesBody/ChatSet.jsx
  src/pages/Chatting/MessagesBody/ImageFullscreen.jsx
  src/pages/Chatting/MessagesBody/index.jsx
  src/pages/Chatting/SideChat.jsx
  src/pages/Chatting/SideChat.tsx
  src/pages/Chatting/WrapChat.jsx
  src/pages/Chatting/index.jsx
  src/pages/Myroom/R2Myroom.jsx
  src/pages/Search/ScrollButton.tsx
  src/routes.ts
  src/tools/isMobile.ts
  src/tools/theme.ts
Labels: 😱 bug, chatting

#508 #501.2 로그인 페이지 부활
  src/App.js
  src/components/Skeleton/ChannelTalkProvider/index.tsx
  src/components/Skeleton/ScrollRestoration/index.tsx
  src/components/Skeleton/index.tsx
  src/components/SuggestLogin.tsx
  src/hooks/useTaxiAPI/useAxios.tsx
  src/pages/Addroom/index.tsx
  src/pages/Error/PageNotFound.tsx
  src/pages/Home/Date.tsx
  src/pages/Home/InfoSection.tsx
  src/pages/Home/RoomSection.tsx
  src/pages/Home/SelectDate.tsx
  src/pages/Home/index.tsx
  src/pages/Login/Logout.tsx
  src/pages/Login/index.jsx
  src/pages/Search/RoomSelectionModal.jsx
  src/tools/random/index.ts
  src/tools/random/roomNames.js
  src/tools/random/taxiSlogans.ts
Labels: loginpage

#522 #507 알림 조회 및 수정 시 Request에서 deviceToken 삭제
  src/components/Skeleton/index.tsx
  src/pages/Mypage/ModalNotification/index.tsx
Labels: mypage

#502 #501 홈페이지와 검색 페이지에 로그인하지 않고 접근하기
  src/components/Button/index.tsx
  src/components/Link/LinkLogin.tsx
  src/components/Link/LinkLogout.tsx
  src/components/Skeleton/ChannelTalkProvider/index.tsx
  src/components/Skeleton/ScrollRestoration/index.tsx
  src/components/Skeleton/index.tsx
  src/components/SuggestLogin.tsx
  src/hooks/useTaxiAPI/useAxios.tsx
  src/pages/Addroom/index.tsx
  src/pages/Error/PageNotFound.tsx
  src/pages/Home/Date.tsx
  src/pages/Home/InfoSection.tsx
  src/pages/Home/RoomList.tsx
  src/pages/Home/RoomSection.tsx
  src/pages/Home/SelectDate.tsx
  src/pages/Home/index.tsx
  src/pages/Login/Logout.tsx
  src/pages/Login/index.jsx
  src/pages/Mypage/index.tsx
  src/pages/Myroom/index.jsx
  src/pages/Search/RoomSelectionModal.jsx
  src/routes.ts
  src/tools/random/index.ts
  src/tools/random/roomNames.js
  src/tools/random/taxiSlogans.ts
Labels: newroom, mypage, loginpage, home

#529 #527 Modal 및 setRecoilValue 리펙토링
  src/atoms/loginInfo.ts
  src/atoms/myRoom.ts
  src/atoms/myRooms.ts
  src/atoms/notificationOptions.ts
  src/atoms/taxiLocation.js
  src/atoms/taxiLocations.ts
  src/components/Link/LinkLogout.tsx
  src/components/ModalPopup/ModalCredit.jsx
  src/components/ModalPopup/ModalModify.jsx
  src/components/ModalPopup/ModalNotification.tsx
  src/components/ModalPopup/ModalPrivacyPolicy.tsx
  src/components/ModalPopup/ModalReport/ReportList.tsx
  src/components/ModalPopup/ModalReport/ReportOption.tsx
  src/components/ModalPopup/ModalReport/index.tsx
  src/components/ModalPopup/ModalTerms.jsx
  src/components/ModalPopup/NotificationGuide.tsx
  src/components/ModalPopup/index.tsx
  src/components/ModalRoomOptions/Place.jsx
  src/components/ProfileImg.jsx
  src/components/Room/index.jsx
  src/components/Skeleton/AlertProvider.tsx
  src/components/Skeleton/ChannelTalkProvider/index.tsx
  src/components/Skeleton/FirebaseMessagingProvider.tsx
  src/components/Skeleton/FlutterEventCommunicationProvider.tsx
  src/components/Skeleton/GoogleAnalyticsProvier.tsx
  src/components/Skeleton/index.tsx
  src/hooks/useFetchRecoilState/index.tsx
  src/hooks/useFetchRecoilState/useFetchLoginInfo.tsx
  src/hooks/useFetchRecoilState/useFetchMyRooms.tsx
  src/hooks/useFetchRecoilState/useFetchNotificationOptions.tsx
  src/hooks/useFetchRecoilState/useFetchTaxiLocations.tsx
  src/hooks/useTaxiAPI/useAxios.tsx
  src/pages/Addroom/index.tsx
  src/pages/Chatting/Header/HeaderBody.jsx
  src/pages/Chatting/Header/Popup/PopupCancel.jsx
  src/pages/Chatting/Header/Popup/PopupPay.jsx
  src/pages/Chatting/Header/Popup/PopupSend.jsx
  src/pages/Chatting/MessageForm/Popup/PopupAccount.tsx
  src/pages/Chatting/MessagesBody/ChatSet.jsx
  src/pages/Chatting/MessagesBody/PopupReport.tsx
  src/pages/Chatting/MessagesBody/index.jsx
  src/pages/Chatting/index.jsx
  src/pages/Home/InfoSection.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.jsx
  src/pages/Mypage/index.tsx
  src/pages/Myroom/index.jsx
  src/pages/Search/RoomSelectionModal.jsx
  src/tools/regExpTest.js
Labels: mypage, 🔨refactoring

#531 #526 홈페이지 Footer 추가
  src/components/Empty.tsx
  src/components/Footer.tsx
  src/components/Skeleton/Footer.tsx
  src/components/Skeleton/Navigation.tsx
  src/components/Skeleton/index.tsx
  src/components/Title.jsx
  src/pages/Event/Event2022Beta.jsx
  src/pages/Event/Event2023Spring.tsx
  src/pages/Event/index.tsx
  src/pages/Home/EventSection.tsx
  src/pages/Home/InfoSection.tsx
  src/pages/Home/RoomList.tsx
  src/pages/Home/RoomSection.tsx
  src/pages/Home/index.tsx
  src/pages/Mypage/index.tsx
  src/routes.ts
Labels: common, home

#532 #528 [Bug] 날짜 옵션으로만 방 검색하기 안됨
  src/components/ModalPopup/ModalRoomSelect.jsx
  src/components/ScrollUpButton.tsx
  src/pages/Addroom/index.tsx
  src/pages/Home/RoomSection.tsx
  src/pages/Search/ScrollButton.tsx
  src/pages/Search/SelectSearchOptions.tsx
  src/pages/Search/SideResult.jsx
  src/pages/Search/index.jsx
  src/pages/Search/utils.ts
  src/tools/moment.js
Labels: 😱 bug, searchroom

#537 #536 Scroll Picker 투명 오류
  src/components/ModalRoomOptions/Picker.css
Labels: 😱 bug

#548 #547 방 공유하기에 에브리타임에 글을 올릴 수 있는 템플릿 생성 후 복사 기능 추가
  src/components/ModalPopup/Body/BodyRoomShare.tsx
  src/tools/moment.js
Labels: common

#542 #541 `day.js` 도입
  package-lock.json
  package.json
  src/hooks/useTaxiAPI/useAxios.tsx
  src/tools/day.ts
Labels: tool

#549 #544 [Bug] 출발 시각이 지난 방을 공유 링크로 접근 시, 모달이 뜨지 않음
  src/components/Footer.tsx
  src/components/ModalPopup/Body/BodyRoomSelection.tsx
  src/pages/Home/RoomSection.tsx
  src/pages/Home/index.tsx
Labels: common

#524 #523 Flutter와 event 기반 통신
  src/App.js
  src/components/Link/LinkLogout.tsx
  src/components/ModalPopup/ModalNotification.tsx
  src/components/Skeleton/FlutterEventCommunicationProvider.tsx
  src/hooks/useFetchRecoilState/index.tsx
  src/pages/Mypage/index.tsx
  src/tools/sendEventToFlutter.ts
  src/tools/trans.js
Labels: common

#538 #506 방 이름 정규식에서 '~'를 비롯한 특수문자 허용
  src/pages/Addroom/index.tsx
  src/pages/Search/index.jsx
  src/tools/random/roomNames.js
  src/tools/regExpTest.js
Labels: ⚒ enhancement, newroom, searchroom, 🖥 working

#551 #523.2 Flutter와 event 기반 통신
  src/atoms/loginInfo.ts
  src/components/Link/LinkLogin.tsx
  src/pages/Login/index.jsx
Labels: common

#504 #503 Introduce `SocketToastProvider`
  src/App.js
  src/components/Skeleton/SocketToastProvider.tsx
  src/pages/Chatting/index.jsx
  src/static/members.js
  src/static/taxiProject.md
  src/tools/socket.ts
  src/types/global.d.ts
Labels: chatting, common

#556 #465.4 개인정보처리방침 링크 생성
  src/pages/Home/index.tsx
Labels: home

#559 #545 안드로이드 기기 모바일에서 홈 페이지 접근 시, 택시 앱 유도 창 띄우기
  src/components/ModalPopup/ModalRoomShare.tsx
  src/components/ModalPopup/ModalSuggestApp.tsx
  src/components/Skeleton/index.tsx
  src/components/Suggest/SuggestApp.tsx
  src/components/WhiteContainer/WhiteContainerSuggestLogin.tsx
  src/components/WhiteContainer/index.tsx
  src/pages/Addroom/index.tsx
  src/pages/Chatting/Header/FullChatHeader.jsx
  src/pages/Home/SuggestAppSection.tsx
  src/pages/Home/index.tsx
  src/pages/Mypage/index.tsx
  src/pages/Myroom/R2Myroom.jsx
  src/pages/Myroom/index.jsx
Labels: skeleton
