Repository sparcs-kaist/taxi-front, pull requests merged in 2024-07, with the labels that each got.

#799 #798 방 이름이 길 때 인원수 표시가 찌그러짐
  packages/web/src/components/Room/index.jsx
Labels: 😱 bug

#777 #773 채팅 140자 넘으면 입력 막기 & 글자 수 circular progress bar로 표시
  packages/web/package.json
  packages/web/src/components/Chat/MessageForm/InputText/BodyText.tsx
  packages/web/src/components/Chat/MessagesBody/MessageSet/MessageText.tsx
  packages/web/src/hooks/chat/useSendMessage.tsx
  packages/web/src/tools/regExpTest.js
  pnpm-lock.yaml
Labels: chatting

#772 랜덤 생성 방 이름 추가
  packages/web/src/tools/random/roomNames.ts
Labels: newroom

#762 예상 택시 비용 보여주기
  packages/web/src/components/Chat/Header/SideMenu.tsx
  packages/web/src/components/ModalPopup/Body/BodyRoomSelection.tsx
  packages/web/src/components/ModalRoomOptions/TaxiFare.tsx
  packages/web/src/components/ModalRoomOptions/index.tsx
  packages/web/src/pages/Addroom/index.tsx
Labels: ⚒ enhancement
